# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a1b6fb34862662821cf2321cd17ad3f7f6de3350714e2c464ad6a837f2d3eede6fd79e6a92707ac59b96cf267705061559f4b46bb52e25f9f51ee3c03b3473

test:
  secret_key_base: 94c7b11e5e7e2c875c5a4de6ea0e658c0468cacb80dbaaf0e496f6d4da34264dfadceb9391ef36fba2de9173062ada7a911def42ad8d15336548300db4370096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
